version: '3'
services:
  app:
    build: .
    container_name: github-app
    environment:
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./github:/app/github